version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    ports:
      - "4560:4560"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  spring-boot-service:
    build:
      context: spring-boot-service/
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge
