apiVersion: v1
kind: ReplicationController
metadata:
  name: log-to-elk-stack-rc
spec:
  replicas: 1
  selector:
    app: log-to-elk-stack
  template:
    metadata:
      name: log-to-elk-stack-template
      labels:
        app: log-to-elk-stack
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
          ports:
            - containerPort: 9200
            - containerPort: 9300
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:6.6.1
          ports:
            - containerPort: 4560
            - containerPort: 9600
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.6.1
          ports:
            - containerPort: 5601