kind: Service
apiVersion: v1
metadata:
  name: log-to-elk-stack-service
  labels:
    app: log-to-elk-stack
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5601
    nodePort: 30555
  selector:
    app: log-to-elk-stack