apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: elk-logger-deployment
spec:
  selector:
    matchLabels:
      app: elk-logger
  replicas: 1
  template:
    metadata:
      labels:
        app: elk-logger
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
          ports:
            - containerPort: 9200
            - containerPort: 9300
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:6.6.1
          ports:
            - containerPort: 4560
            - containerPort: 9600
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.6.1
          ports:
            - containerPort: 5601
